name: Deploy Infraestructura

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:

      # Descargar el repositorio
      - name: Checkout código
        uses: actions/checkout@v3

      #  Instalar Terraform
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.5

      #  Instalar Ansible
      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      # Validar Terraform
      - name: Validar Terraform
        run: |
          cd terraform
          terraform init
          terraform validate -var="public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"
          terraform fmt -check

      # Validar Ansible
      - name: Validar Ansible
        run: |
          ls -la ansible    # <-- esto para depurar que site.yml esté
          ansible-playbook -i ansible/inventory_aws_ec2.yml ansible/site.yml --syntax-check

      #  Aplicar Terraform
      - name: Aplicar Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"

      #  Guardar clave privada SSH
      - name: Configurar clave privada SSH
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ansible/mi_clave.pem
          chmod 600 ansible/mi_clave.pem

      #  Ejecutar Ansible
      - name: Ejecutar Ansible
        run: |
          ansible-playbook -i ansible/inventory_aws_ec2.yml ansible/site.yml --private-key ansible/mi_clave.pem
