name: Deploy Infraestructura

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:

      # 1. Descargar el repositorio
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Instalar Terraform
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.5

      # 3. Instalar Ansible
      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass python3-pip
          pip3 install boto3 botocore

      # 4. Validación de Terraform
      - name: Validar Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform validate
          terraform fmt -check -diff || true

      # 5. Validación de Ansible
      - name: Validar Ansible
        working-directory: ansible
        run: |
          ansible-playbook -i inventory_aws_ec2.yml site.yml --syntax-check

      # 6. Aplicar Terraform (crear la infraestructura)
      - name: Aplicar Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve -var="public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"

      # 7. Guardar la clave privada SSH
      - name: Configurar clave privada SSH
        working-directory: ansible
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > mi_clave.pem
          chmod 600 mi_clave.pem

      # 8. Ejecutar Ansible en los servidores creados
      - name: Ejecutar Ansible
        working-directory: ansible
        run: |
          ansible-playbook -i inventory_aws_ec2.yml site.yml --private-key mi_clave.pem
